### ISSUE TITLE
Avoid remote import in XSL file

### ISSUE THREAD

**Issue by gunnarmorling** [pressgang/pressgang-tools#3]
In https://github.com/pressgang/pressgang-tools/blob/master/pressgang-xslt-ns/src/main/resources/xslt/org/jboss/pressgang/xhtml.xsl there is a remote import to another XSL file on SourceForge. Ideally, this should be replaced with a local copy of that file to avoid issues during outages as the recent SF downtime.

**Comment by ge0ffrey** [comment]
jdocbook-core (which is used by the maven and gradle plugin) automatically do that: they notice the url, replace it with their local copy (if the versions match!) and do not use the internet to build.
That being said, there were issues with that: but I know it works well with the latest maven plugin, the latest pressgang tools, etc. See the pressgangs-tools-example here, or the optaplanner-docs build (which inherits from kie-parent-metadata).

**Comment by gunnarmorling** [comment]
Thanks for your reply, Geoffrey!

We had at least one case where this didn't work as per @hferentschik's
report: http://lists.jboss.org/pipermail/hibernate-dev/2015-July/013117.html.
Maybe we are not on the latest versions, though. Need to check that.

**Comment by hferentschik** [comment]
FYI, this was part of the ORM documentation build. This uses the gradle docbook plugin - https://github.com/gradle/gradle-jdocbook which in turn seems to use version 1.1.0 of jdocbook-core - https://github.com/gradle/gradle-jdocbook/blob/master/build.gradle#L58. Would that version be obsolete? Maybe it is a question of upgrading the version used in the gradle plugin?

**Comment by ge0ffrey** [comment]
The gradle plugin should define the jdcobook-core version, you only need to use the correct (=latest) gradle plugin version and presggang-* version.

**Comment by ge0ffrey** [comment]
cc @psiroky

**Comment by hferentschik** [comment]
FYI - https://github.com/gradle/gradle-jdocbook/pull/21

**Comment by ge0ffrey** [comment]
Thanks, Closing the issue on this side.
